CS349 WatGUI: cs349::StopWatch Class Reference
cs349::StopWatch Class Reference
#include "StopWatch.h"
Public Member Functions
StopWatch (EventQueue *eventQueue, const Rectangle &bounds)
virtual ~StopWatch ()
virtual bool HandleMouseEvent (const MouseEvent &e)
virtual void Paint (Graphics *g)
virtual void HandleTimerEvent (const cs349::TimerEvent &e)
void Start ()
void Stop ()
bool IsRunning () const
bool IsReset () const
void ChangeStartPauseBtn (char *status)
void UpdateBtn1Width ()
int CheckBtnBoundary (const Point &p)
void ResetStopWatch ()
void UpdateNumericalDisplay (bool resume=false)
void UpdateAbstractDisplay ()
void UpdateButton ()
Public Member Functions inherited from cs349::XWindow
XWindow (const string &title, const Rectangle &bounds)
virtual ~XWindow ()
virtual Graphics * GetGraphics ()
virtual void HandlePaintEvent (const PaintEvent &e)
virtual void SetTitle (const char *title)
virtual Rectangle GetBounds () const
virtual void PaintComponent (Graphics *g)
virtual XWindow * GetParentWindow ()
virtual void Repaint (const Rectangle &r)
virtual void SetBounds (const Rectangle &r)
virtual void SetLocation (const Point &p)
virtual void SetParent (Component *parent)
virtual void SetSize (int width, int height)
virtual void SetVisible (bool visible)
long GetWindowNum () const
Public Member Functions inherited from cs349::Component
Component (const string &name)
virtual ~Component ()
virtual string GetName () const
virtual void AddComponent (Component *child)
virtual void RemoveComponent (Component *child)
virtual unsigned long GetBackgroundColor () const
virtual unsigned long GetForegroundColor () const
virtual Component * GetParent ()
virtual bool HandleKeyEvent (const KeyEvent &e)
virtual bool IsPointInComponent (const Point &p) const
virtual bool IsVisible () const
virtual void Repaint ()
virtual void SetBackgroundColor (unsigned long c)
virtual void SetForegroundColor (unsigned long c)
virtual void SetDebugDelay (unsigned long delayMS)
long GetComponentNum () const
vector< Component * > GetDepthFirstInteractorTree () const
vector< Component * > GetBreadthFirstInteractorTree () const
Static Private Member Functions
static unsigned long GetCurTime ()
Private Attributes
Timer * timer
unsigned long startTimeMS
bool running
string btn1
const string btn2 = "RESET"
const int btn1_x = 49
const int btn1_y = 170
const int btn2_x = 109
const int btn2_y = 170
const int btn_height = 20
const int btn2_width = btn2.length()*10
int btn1_width = 50
int msec
int sec
int min
int elapsed
Additional Inherited Members
Static Public Member Functions inherited from cs349::XWindow
static XWindow * GetXWindowForWindow (Window window)
static vector< XWindow * > GetWindowList ()
static XWindow * GetXWindow (long windowNum)
Protected Attributes inherited from cs349::Component
vector< Component * > children
All the children of this Component.
Private Member Functions inherited from cs349::TimerListener
TimerListener ()
virtual ~TimerListener ()
Detailed Description
Skeleton of a StopWatch class to complete and augment for A1
Definition at line 17 of file StopWatch.h.
Constructor & Destructor Documentation
cs349::StopWatch::StopWatch (EventQueue * eventQueue, const Rectangle & bounds)
StopWatch derives from XWindow and TimerListener. These classes require the following information passed in.
Parameters
eventQueue The XApplication's event queue
bounds The desired location and size of this StopWatch window.
Definition at line 11 of file StopWatch.cpp.
References btn1, elapsed, min, msec, running, sec, cs349::Timer::Start(), startTimeMS, and timer.
                                                                        : XWindow(string("Stop Watch!"), bounds) {
     this->running = false;
     this->timer = new Timer(eventQueue, 100, true, this);
     timer->Start();
     startTimeMS = 0;
     this->btn1 = "START";
     msec = 0;
     sec = 0;
     min = 0;
     elapsed = 0;
   }
cs349::StopWatch::~StopWatch () virtual
Definition at line 24 of file StopWatch.cpp.
References cs349::Timer::Stop(), and timer.
{
     timer->Stop();
     delete timer;
     timer = NULL;
   }
Member Function Documentation
void cs349::StopWatch::ChangeStartPauseBtn (char * status)
Definition at line 163 of file StopWatch.cpp.
References btn1.
Referenced by HandleMouseEvent().
{
     this->btn1 = str;
   }
int cs349::StopWatch::CheckBtnBoundary (const Point & p)
Definition at line 171 of file StopWatch.cpp.
References btn_height, cs349::Point::x, and cs349::Point::y.
Referenced by HandleMouseEvent().
{
     int btn_num;
       if((p.x >= this->btn1_x && p.x <= (this->btn1_x+this->btn1_width))
           && (p.y >= this->btn1_y && p.y <= (this->btn1_y+btn_height))){
         btn_num = 1;
       }else if((p.x >= this->btn2_x && p.x <= (this->btn2_x+this->btn2_width))
                 && (p.y >= this->btn2_y && p.y <= (this->btn2_y+btn_height))){
         btn_num = 2;
       }else{
         btn_num = 0;
       }
     return btn_num;
   }
unsigned long cs349::StopWatch::GetCurTime () static private
Returns the current time in milliseconds.
Definition at line 30 of file StopWatch.cpp.
Referenced by HandleMouseEvent(), Paint(), and Start().
{
     struct timespec tp;
     clock_gettime(CLOCK_REALTIME, &tp);
     return tp.tv_sec * 1000 + tp.tv_nsec / 1000000;
   }
bool cs349::StopWatch::HandleMouseEvent (const MouseEvent & e) virtual
Overrides Component's HandleMouseEvent method.
Reimplemented from cs349::Component.
Definition at line 71 of file StopWatch.cpp.
References btn1, ChangeStartPauseBtn(), CheckBtnBoundary(), elapsed, GetCurTime(), cs349::MouseEvent::GetWhere(), IsRunning(), ResetStopWatch(), Start(), startTimeMS, Stop(), and UpdateButton().
{
     // TODO: Remove the following code and add your own event handling
     // code to handle mouse events
     // LOG_DEBUG << "Received HandleMouseEvent in StopWatch" << e;
     // FOR BTN1
     // _________________________________
     // |phase 1: !running && timer == 0|
     // |   -----   -----               |
     // |  |START| |RESET|              |
     // |   -----   -----               |
     // |_______________________________|
     //       |
     //       v
     // ________________________________
     // |phase 2: running && timer > 0 |
     // |   -----   -----              |
     // |  |PAUSE| |RESET|             |
     // |   -----   -----              |
     // |______________________________|
     //       |     ^
     //       v     |
     // ________________________________
     // |phase 3: !running && timer > 0|
     // |   ------   -----             |
     // |  |RESUME| |RESET|            |
     // |   ------   -----             |
     // |______________________________|
 // TODO CS349
     Point p = e.GetWhere();
     switch(this->CheckBtnBoundary(e.GetWhere())){
       case 0:
       break;
       case 1:
       if(!this->IsRunning()){
         if(this->btn1 == "START"){
           this->ChangeStartPauseBtn("PAUSE");
           this->Start();
         }else{
           this->ChangeStartPauseBtn("PAUSE");
           this->Start();
           this->UpdateButton();
         }
       }else {
         this->elapsed = this->elapsed + this->GetCurTime() - this->startTimeMS;
         this->Stop();
         this->ChangeStartPauseBtn("RESUME");
         this->UpdateButton();
       }
       break;
       case 2:
       this->Stop();
       this->ResetStopWatch();
       this->ChangeStartPauseBtn("START");
       this->UpdateButton();
       break;
     }
     return true;
   }
void cs349::StopWatch::HandleTimerEvent (const cs349::TimerEvent & e) virtual
Overrides TimerListener's HandleTimerEvent to be able to routinely update the display.
Implements cs349::TimerListener.
Definition at line 135 of file StopWatch.cpp.
References cs349::Component::Repaint(), and running.
{
     if (running) {
       Component::Repaint();
     }
   }
bool cs349::StopWatch::IsReset () const
Definition at line 154 of file StopWatch.cpp.
References IsRunning(), min, msec, and sec.
Referenced by TEST().
{
     if(!this->IsRunning() && this->min == 0 && this->sec == 0 && this->msec == 0){
       return true;
     }
     else{
       return false;
     }
   }
bool cs349::StopWatch::IsRunning () const
Query whether the stopwatch is running or not.
Definition at line 150 of file StopWatch.cpp.
References running.
Referenced by HandleMouseEvent(), IsReset(), and TEST().
{
     return running;
   }
void cs349::StopWatch::Paint (Graphics * g) virtual
Overrides Component's Paint method.
Reimplemented from cs349::Component.
Definition at line 36 of file StopWatch.cpp.
References btn1, btn1_width, btn1_x, btn1_y, btn2, btn2_width, btn2_x, btn2_y, btn_height, cs349::Graphics::DrawRect(), cs349::Graphics::DrawText(), elapsed, cs349::Graphics::FillRect(), GetCurTime(), min, msec, sec, cs349::Graphics::SetForegroundColor(), startTimeMS, UpdateAbstractDisplay(), UpdateBtn1Width(), and UpdateNumericalDisplay().
{
 // TODO CS349
     g->SetForegroundColor(0x000000);
     g->FillRect(Rectangle(0, 0, 200, 210));
     //boundary of rectangle
     g->SetForegroundColor(0xFFFFFF);
     g->DrawRect(Rectangle(5, 5, 190, 200));
     //numerical display
     //calculate min, sec, millisec
     if(this->startTimeMS != 0){
       int diff = this->GetCurTime()-this->startTimeMS+this->elapsed;
       this->min = diff/60000%10;
       this->sec = (diff%60000)/1000;
       this->msec = (diff%60000)%1000;
     }
     //convert int to string
     this->UpdateNumericalDisplay();
     this->UpdateAbstractDisplay();
     //start button
     this->UpdateBtn1Width();
     g->DrawRect(Rectangle(this->btn1_x, this->btn1_y, this->btn1_width, this->btn_height));
     g->DrawText(Point((this->btn1_x+10), (this->btn1_y+15)), this->btn1);
     //reset button
     g->DrawRect(Rectangle(this->btn2_x, this->btn2_y, this->btn2_width, this->btn_height));
     g->DrawText(Point((this->btn2_x+10), (this->btn2_y+15)), this->btn2);
   }
void cs349::StopWatch::ResetStopWatch ()
Definition at line 191 of file StopWatch.cpp.
References elapsed, min, msec, sec, startTimeMS, UpdateAbstractDisplay(), and UpdateNumericalDisplay().
Referenced by HandleMouseEvent().
{
     this->startTimeMS = 0;
     this->msec = 0;
     this->sec = 0;
     this->min = 0;
     this->elapsed = 0;
     this->UpdateNumericalDisplay(true);
     this->UpdateAbstractDisplay();
   }
void cs349::StopWatch::Start ()
Start the stopwatch
Definition at line 141 of file StopWatch.cpp.
References GetCurTime(), running, and startTimeMS.
Referenced by HandleMouseEvent().
{
     this->running = true;
     startTimeMS = GetCurTime();
   }
void cs349::StopWatch::Stop ()
Stop the stopwatch
Definition at line 146 of file StopWatch.cpp.
References running.
Referenced by HandleMouseEvent().
{
     this->running = false;
   }
void cs349::StopWatch::UpdateAbstractDisplay ()
Definition at line 227 of file StopWatch.cpp.
References cs349::Graphics::DrawRect(), cs349::Graphics::DrawText(), cs349::Graphics::FillRect(), cs349::XWindow::GetGraphics(), min, msec, sec, and cs349::Graphics::SetForegroundColor().
Referenced by Paint(), and ResetStopWatch().
{
     Graphics* g = XWindow::GetGraphics();
     int ab_min = this->min%10*10;
     int ab_sec = this->sec%60/6*10;
     int ab_msec = this->msec%1000/10;
     //abstract graphic display for min, sec, ms in order
     g->SetForegroundColor(0x000000);
     g->FillRect(Rectangle(55, 40, 100, 130));
     g->SetForegroundColor(0xFFFFFF);
     //percentage display
     stringstream ss;
     ss << ab_min << " %";
     g->DrawText(Point(57, 160), ss.str());
     ss.str("");
     ss << ab_sec << " %";
     g->DrawText(Point(94, 160), ss.str());
     ss.str("");
     ss << ab_msec << " %";
     g->DrawText(Point(131, 160), ss.str());
     ss.str("");
     //animation filling rectangles
     g->DrawRect(Rectangle(55, 40, 18, 100));
     g->FillRect(Rectangle(55, 40, 18, ab_min));
     g->DrawRect(Rectangle(92, 40, 18, 100));
     g->FillRect(Rectangle(92, 40, 18, ab_sec));
     g->DrawRect(Rectangle(129, 40, 18, 100));
     g->FillRect(Rectangle(129, 40, 18, ab_msec));
   }
void cs349::StopWatch::UpdateBtn1Width ()
Definition at line 167 of file StopWatch.cpp.
References btn1, and btn1_width.
Referenced by Paint().
{
     this->btn1_width = this->btn1.length()*10;
   }
void cs349::StopWatch::UpdateButton ()
Definition at line 266 of file StopWatch.cpp.
References btn1, btn1_width, btn1_x, btn1_y, btn_height, cs349::Graphics::DrawRect(), cs349::Graphics::DrawText(), cs349::Graphics::FillRect(), cs349::XWindow::GetGraphics(), and cs349::Graphics::SetForegroundColor().
Referenced by HandleMouseEvent().
{
     Graphics* g = XWindow::GetGraphics();
     g->SetForegroundColor(0x000000);
     g->FillRect(Rectangle(this->btn1_x, this->btn1_y, this->btn1_width, this->btn_height));
     g->SetForegroundColor(0xFFFFFF);
     g->DrawRect(Rectangle(this->btn1_x, this->btn1_y, this->btn1_width, this->btn_height));
     g->DrawText(Point(this->btn1_x+10, this->btn1_y+15), this->btn1);
   }
void cs349::StopWatch::UpdateNumericalDisplay (bool resume = false)
Definition at line 201 of file StopWatch.cpp.
References cs349::Graphics::DrawText(), cs349::Graphics::FillRect(), cs349::XWindow::GetGraphics(), min, msec, sec, and cs349::Graphics::SetForegroundColor().
Referenced by Paint(), and ResetStopWatch().
{
     Graphics* g = XWindow::GetGraphics();
     stringstream ss;
     ss << this->min;
     if(resume){
       g->SetForegroundColor(0x000000);
       g->FillRect(Rectangle(50, 20, 100, 18));
     }
     g->SetForegroundColor(0xFFFFFF);
     g->DrawText(Point(60, 35), ss.str());
     ss.str("");
     g->DrawText(Point(80, 35), ":");
     ss << this->sec;
     g->DrawText(Point(95, 35), ss.str());
     ss.str("");
     g->DrawText(Point(117, 35), ":");
     ss << this->msec;
     g->DrawText(Point(130, 35), ss.str());
   }
Member Data Documentation
string cs349::StopWatch::btn1 private
Definition at line 36 of file StopWatch.h.
Referenced by ChangeStartPauseBtn(), HandleMouseEvent(), Paint(), StopWatch(), UpdateBtn1Width(), and UpdateButton().
int cs349::StopWatch::btn1_width = 50 private
Definition at line 44 of file StopWatch.h.
Referenced by Paint(), UpdateBtn1Width(), and UpdateButton().
const int cs349::StopWatch::btn1_x = 49 private
Definition at line 38 of file StopWatch.h.
Referenced by Paint(), and UpdateButton().
const int cs349::StopWatch::btn1_y = 170 private
Definition at line 39 of file StopWatch.h.
Referenced by Paint(), and UpdateButton().
const string cs349::StopWatch::btn2 = "RESET" private
Definition at line 37 of file StopWatch.h.
Referenced by Paint().
const int cs349::StopWatch::btn2_width = btn2.length()*10 private
Definition at line 43 of file StopWatch.h.
Referenced by Paint().
const int cs349::StopWatch::btn2_x = 109 private
Definition at line 40 of file StopWatch.h.
Referenced by Paint().
const int cs349::StopWatch::btn2_y = 170 private
Definition at line 41 of file StopWatch.h.
Referenced by Paint().
const int cs349::StopWatch::btn_height = 20 private
Definition at line 42 of file StopWatch.h.
Referenced by CheckBtnBoundary(), Paint(), and UpdateButton().
int cs349::StopWatch::elapsed private
Definition at line 48 of file StopWatch.h.
Referenced by HandleMouseEvent(), Paint(), ResetStopWatch(), and StopWatch().
int cs349::StopWatch::min private
Definition at line 47 of file StopWatch.h.
Referenced by IsReset(), Paint(), ResetStopWatch(), StopWatch(), UpdateAbstractDisplay(), and UpdateNumericalDisplay().
int cs349::StopWatch::msec private
Definition at line 45 of file StopWatch.h.
Referenced by IsReset(), Paint(), ResetStopWatch(), StopWatch(), UpdateAbstractDisplay(), and UpdateNumericalDisplay().
bool cs349::StopWatch::running private
Whether the stopwatch is currently running.
Definition at line 33 of file StopWatch.h.
Referenced by HandleTimerEvent(), IsRunning(), Start(), Stop(), and StopWatch().
int cs349::StopWatch::sec private
Definition at line 46 of file StopWatch.h.
Referenced by IsReset(), Paint(), ResetStopWatch(), StopWatch(), UpdateAbstractDisplay(), and UpdateNumericalDisplay().
unsigned long cs349::StopWatch::startTimeMS private
The time, in milliseconds, that the stopwatch started
Definition at line 28 of file StopWatch.h.
Referenced by HandleMouseEvent(), Paint(), ResetStopWatch(), Start(), and StopWatch().
Timer* cs349::StopWatch::timer private
Timer used to periodically update the stopwatch's display
Definition at line 23 of file StopWatch.h.
Referenced by StopWatch(), and ~StopWatch().
The documentation for this class was generated from the following files:
StopWatch.h
StopWatch.cpp